openapi: 3.0.0
info:
  title: Voosh Assgiment
  version: 1.0.0
servers:
  - url: http://localhost
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Users
  - name: Auth
paths:
  /users/signup/email:
    post:
      tags:
        - Users
      summary: Create new account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: sachin
                email: 1234@gmail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    put:
      tags:
        - Users
      summary: Update Details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: sachin
                password: '123456'
                isPublic: true
                email: 123@gmail.com
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Users
      summary: Get Self user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/photo:
    put:
      tags:
        - Users
      summary: Update Photo
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/signup/google:
    get:
      tags:
        - Users
      summary: Create Account With google
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}:
    get:
      tags:
        - Users
      summary: get user by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/email:
    post:
      tags:
        - Auth
      summary: login with email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: 1234@gmail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}